name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - sympy
  - matplotlib
  - seaborn
  - plotly
  - folium
  - openpyxl
  - xlrd
  - selenium
  - wordcloud
  - feature_engine
  - mlxtend
  - kaggle
  - beautifulsoup4
  - streamlit
  - dash
  - dash-core-components
  - pandas-profiling
  - django
  - flask
  - imbalanced-learn
  - xgboost
  - tensorflow-cpu
  - tensorflow-hub
  - pytorch-cpu
  - keras-tuner
  - pydot
  - opencv
  - transformers
  - nltk
  - nltk_data
  - spacy
  - spacy-model-en_core_web_md

  - pip:
    - PySastrawi
